# Generated by Django 5.0.6 on 2024-06-01 12:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_content_delete_postcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_cover_path),
        ),
    ]
