# Generated by Django 5.0.6 on 2024-06-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
