# Generated by Django 5.0.6 on 2024-05-31 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_info_postcontent_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='api.post'),
        ),
    ]
