# Generated by Django 5.0.6 on 2024-06-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tag_alter_post_title_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
