# Generated by Django 5.0.6 on 2024-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_comment_user_comment_name_comment_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='site',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
