# Generated by Django 5.0.6 on 2024-05-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_post_summary_postcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='info',
            new_name='post',
        ),
    ]
